### ISSUE TITLE
Manual Home Assistant YAML - Soldered Install

### ISSUE THREAD

**Issue by tony-fav** [PaulWieland/ratgdo#15]
I just wanted to share my HA yaml configuration for anyone else interested.

It's a bit more complicated than it could be. It would be significantly simpler if the status topic was split into door_state, obstruction_state, and LWT. Additionally, if state publications were retained, it would know status on HA restart.

This created 4 entities: the cover itself, the light button, the obstruction binary sensor, and a button for the `query` command which is useful for getting the other entities back to an available state if HA restarts.

![image](https://user-images.githubusercontent.com/42725386/196545212-f1f8cc62-7480-4be0-9492-f1552655beca.png)

```yaml
mqtt:
  cover:
    - name: "RATGDO"
      unique_id: ratgdo
      command_topic: "ratgdo/command"
      state_topic: "ratgdo/status"
      availability:
        - topic: "ratgdo/status"
          value_template: |-
            {% if value == "offline" %}
              offline
            {% else %}
              online
            {% endif %}
      payload_open: "open"
      payload_close: "close"
      payload_stop: 
      state_open: "open"
      state_opening: "opening"
      state_closed: "closed"
      state_closing: "closing"
      payload_available: "online"
      payload_not_available: "offline"
      optimistic: false
      value_template: |-
        {% if value == "open" %}
          open
        {% elif value == "opening" %}
          opening
        {% elif value == "closed" %}
          closed
        {% elif value == "closing" %}
          closing
        {% else %}
          {{ states("cover.ratgdo") }}
        {% endif %}
      device_class: garage
        
  button:
    - name: "RATGDO Get Status"
      unique_id: ratgdo_status
      command_topic: "ratgdo/command"
      payload_press: "query"
      device_class: restart
      
    - name: "RATGDO Light"
      unique_id: ratgdo_light
      availability:
        - topic: "ratgdo/status"
          value_template: |-
            {% if value == "offline" %}
              offline
            {% else %}
              online
            {% endif %}
      command_topic: "ratgdo/command"
      payload_press: "light"
      icon: mdi:light-recessed
  
  binary_sensor:
    - name: "RATGDO Obstruction"
      unique_id: ratgdo_obstruction
      availability:
        - topic: "ratgdo/status"
          value_template: |-
            {% if value == "offline" %}
              offline
            {% else %}
              online
            {% endif %}
      state_topic: "ratgdo/status"
      payload_on: obstructed
      payload_off: clear
      value_template: |-
        {% if value == "obstructed" %}
          obstructed
        {% elif value == "clear" %}
          clear
        {% else %}
          {{ states("binary_sensor.ratgdo_obstruction") }}
        {% endif %}
      device_class: safety
```

Edit: I should note this is for a soldered configuration, and I fortunately have a *50 board.
