### ISSUE TITLE
How to add to esphome?

### ISSUE THREAD

**Issue by abishur** [PaulWieland/ratgdo#21]
Is there anyway to add the install configuration files to esphome so I can manage this device along side my other ESPhome devices?

**Comment by jcam** [comment]
The project would need to be modified quite a bit to pull out just the door control stuffs as sensors and switches, split from the wifi/mqtt/etc stuff that ESPhome handles itself. If this continues to not get traction, maybe I'll poke at it once my shields arrive.

**Comment by kantlivelong** [comment]
Not requiring ESPHome is great but I agree that an ESPHome compatible library/component would be really cool.

Once the 2.x source is pushed out I'll likely take a look at what adjustments can be made to make the code compatible with both.

**Comment by bdraco** [comment]
I tried to port it to esphome but I couldn't get it to read the UART correctly.  I might have the pins wrong though

https://github.com/bdraco/esphome-ratgdo

**Comment by bdraco** [comment]
```
---
esphome:
  name: ratgdo
  platform: ESP8266
  board: esp01_1m

api:
  id: api_server

external_components:
  - source:
      type: git
      url: https://github.com/bdraco/esphome-ratgdo
    refresh: 1s

uart:
  tx_pin: 2
  rx_pin: 4
  baud_rate: 9600

ratgdo:

# WiFi connection, correct these
# with values for your WiFi.
wifi:
  ssid: <fill>
  password: <fill>

logger:
#  level: VERBOSE


# Enable over-the-air updates.
ota:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


```

**Comment by kantlivelong** [comment]
> I've got the esphome lib reading state now.

Nice! Is this written for the V1 or V2 board?

**Comment by bdraco** [comment]
```
[08:50:07][V][mdns:112]:   - _http, _tcp, 80
[08:50:07][C][ota:093]: Over-The-Air Updates:
[08:50:07][C][ota:094]:   Address: overlookratgdo.local:8266
[08:50:07][C][api:138]: API Server:
[08:50:07][C][api:139]:   Address: overlookratgdo.local:6053
[08:50:07][C][api:143]:   Using noise encryption: NO
[08:50:11][D][ratgdo:429]: Motion state 1
[08:50:26][D][ratgdo:413]: Door state 4

```

**Comment by bdraco** [comment]
<img width="1021" alt="Screenshot 2023-06-07 at 12 28 06 PM" src="https://github.com/PaulWieland/ratgdo/assets/663432/fd537528-8c73-4ce7-8582-9d6da5aba4db">


Getting close to usable

**Comment by kantlivelong** [comment]
@bdraco Do you think it would be possible to merge into this repo in a way that allows the dedicated firmware and esphome to use the same codebase? Obviously we are still waiting on 2.x source and @PaulWieland would have to be open to the idea but I think that would be a great way to give users choice while using the upstream source.

**Comment by bdraco** [comment]
Working esphome config for shield v2 -- note, you must currently factory reset the GDO before installing since there is no way to set or change the rolling code and it will start at 0

The light is still a bit wonky but will work that out

```
---
esphome:
  name: overlookratgdo
  platform: ESP8266
  board: esp01_1m

api:
  id: api_server

web_server:

external_components:
  - source:
      type: git
      url: https://github.com/bdraco/esphome-ratgdo
    refresh: 1s

ratgdo:
  id: overlook_ratgdo

binary_sensor:
  - platform: ratgdo
    type: motion
    id: ratgdo_motion
    ratgdo_id: overlook_ratgdo
    name: "Overlook Garage Motion"
    device_class: motion
  - platform: ratgdo
    type: obstruction
    id: ratgdo_obstruction
    ratgdo_id: overlook_ratgdo
    name: "Overlook Garage Obstruction"
    device_class: problem

cover:
  - platform: ratgdo
    id: ratgdo_garage
    device_class: garage
    name: "Overlook Garage"
    ratgdo_id: overlook_ratgdo


light:
  - platform: ratgdo
    id: ratgdo_light
    name: "Overlook Garage Light"
    ratgdo_id: overlook_ratgdo

uart:
  tx_pin: 
      number: 2
      inverted: true
  rx_pin:
      number: 4
      inverted: true
  baud_rate: 9600

wifi:
  ssid: YOURSSID
  password: YOURPASSWORD

logger:
  level: VERBOSE

ota:

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time


```
